name: book
type: php:8.2

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - blackfire
        - ctype
        - iconv
        - mbstring
        - pdo_pgsql
        - sodium
        - xsl

variables:
    php:
        opcache.preload: config/preload.php
        memory_limit: 512M
        upload_max_filesize: 64M
        post_max_size: 64M

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads }

relationships:
    database: "mysql:mysql"

hooks:
    build: |
        set -x -e
        curl -fs https://get.symfony.com/cloud/configurator | bash
        NODE_VERSION=18 symfony-build

    deploy: |
        set -x -e
        php bin/console doctrine:migrations:migrate --no-interaction
        # Create upload directories if they don't exist
        mkdir -p public/uploads/book_images
        mkdir -p public/uploads/avatars
        # Set proper permissions
        chmod -R 755 public/uploads
        symfony-deploy

crons:
  # Cron job to run security check daily at 11:50 PM UTC
  security-check:
    spec: '50 23 * * *'  # Run daily at 11:50 PM UTC
    cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi
