https://{default}/:
    type: upstream
    upstream: "book:http"

https://www.{default}/:
    type: redirect
    to: "https://{default}/"

# Define the route for /books, including the correct scheme
https://{default}/books:
    type: upstream
    upstream: "book:http"
